### ISSUE TITLE
Catching a StackOverflowException in a WPF application built in Release

### ISSUE THREAD

**Issue by stuarthillary** [NicolaiNyberg/DbgSvcExtension#1]
I have made a simple WPF application that raises a StackOverflowException by clicking a button (it simply recurses a function until no stack space remains). Like in the SoexCh.Cs example I attach the vectored exception handler by calling into the CrashHandler API. If I build the WPF application in the Debug platform the crash dump is created successfully. However, if I build the WPF app in Release no crash dump is created and the app hangs. It looks like the dumpEvent is not triggered within CrashHandler in this situation. Do you know why this might be?

**Comment by NicolaiNyberg** [comment]
Can you provide me with the smallest app possible that reproduces this error ?

**Comment by stuarthillary** [comment]
I have put together a simple app here 
[https://github.com/stuarthillary/ErrorApp](https://github.com/stuarthillary/ErrorApp)

The app has two buttons, one triggers a AccessViolationException, the other a StackOverflowException. When the App is built in x64 Release the exception handler doesn't seem to be triggered on a StackOverflow.

**Comment by NicolaiNyberg** [comment]
In release mode, technically your ErrorApp is not blowing the stack. The JIT-compiler has optimized this step away - at least on my platform. In other words, it has recognized that you are calling yourself and has replaced the 'call me()' with a 'jmp me()' and the latter does not involve the stack.

I had to ask procexp.exe (from Sysinternals) to create a full dump of the running process and open it in windbg in order to see what was going on.

![errorapp release](https://user-images.githubusercontent.com/8720733/49059977-cf394880-f20b-11e8-8c49-f108d1943327.png)
